config/routes.rb
Rails.application.routes.draw do
  resources :messages, only: [:new, :create, :show]
  get '/messages', to: redirect('/')
  root to: 'messages#index'
  post '/webhooks', to: 'webhooks#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :to,
    :presence => true,
    :format => { :with => /\A[^\s]+@[^\s]+\z/, :message => "doesn't look like an email address" }
  validates :subject, :presence => true
  validates :body, :presence => true

  def status
    self['status'] || "created"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_attributes)
    if @message.save
      MessageMailer.with(message: @message).email.deliver_now!
      redirect_to @message
    else
      render :new
    end
  end

  def show
    @message = Message.find(params[:id])
  end

  private

  def message_attributes
    params.require(:message).permit(:to, :subject, :body)
  end
end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
    skip_before_action :verify_authenticity_token
    def create
        events = params["_json"]
        events.each do |event|
          next unless event["id"]
          message = Message.find(event["id"])
          message.update_attribute(:status, event["event"])
        end
        head :ok
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  STATUS_MAP = {
    'dropped' => 'danger',
    'deferred' => 'warning',
    'bounce' => 'danger',
    'open' => 'success',
    'delivered' => 'info'
  }

  def status_badge(status)
    class_name = "badge badge-#{STATUS_MAP[status] || 'primary'}"
    content_tag(:span, status, class: class_name)
  end
end

app/helpers/webhooks_helper.rb
module WebhooksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SendgridEmailStatus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
      <%= link_to 'Messages', root_path, class: "navbar-brand col-sm-3 col-md-2 mr-0" %>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <%= link_to 'Messages', root_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Send new message', new_message_path, class: 'nav-link' %>
              </li>
           </ul>
          </div>
        </nav>
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
          <%= yield %>
        </main>
      </div>
    </div>
  </body>
</html>

app/views/messages/index.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3">
  <h1 class="h2">Messages</h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group mr-2">
      <%= link_to 'New message', new_message_path, class: 'btn btn-sm btn-outline-secondary' %>
    </div>
  </div>
</div>
<div class="table-responsive">
  <% if @messages.any? -%>
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Subject</th>
          <th scope="col">Status</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @messages.each do |message| -%>
          <tr>
            <td><%= message.id %></td>
            <td><%= message.subject %></td>
            <td><%= status_badge(message.status) %></td>
            <td><%= link_to "show", message_path(message) %></td>
          </tr>
        <% end -%>
      </tbody>
    </table>
  <% else -%>
    <p>You haven't created any messages yet. <%= link_to 'Create your first message', new_message_path %>.</p>
  <% end -%>
</div>

app/views/messages/new.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
  <h1 class="h2">New Message</h1>
</div>

<% if @message.errors.full_messages.any? %>
  <div class="alert alert-danger">
    <h2 class="h6"><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>
    <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @message, :local => true do |f| %>
  <div class="form-group">
    <%= f.label :to %>
    <%= f.email_field :to, :class => "form-control#{ ' is-invalid' if @message.errors[:to].any? }", :required => true %>
  </div>
  <div class="form-group">
    <%= f.label :subject %>
    <%= f.text_field :subject, :class => "form-control#{ ' is-invalid' if @message.errors[:subject].any? }", :required => true %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, :class => "form-control#{ ' is-invalid' if @message.errors[:body].any? }", :required => true %>
  </div>
  <%= f.button "Send", :class => 'btn btn-primary' %>
<% end %>

app/views/messages/show.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
  <h1 class="h2">Message / <%= @message.id %></h1>
</div>

<dl>
  <dt>To</dt>
  <dd><%= @message.to %></dd>
  <dt>Subject</dt>
  <dd><%= @message.subject %></dd>
  <dt>Body</dt>
  <dd><%= simple_format @message.body %></dd>
  <dt>Status</dt>
  <dd><%= status_badge(@message.status) %></dd>
</dl>